"""added owner

Revision ID: 345250e383fd
Revises: 86dee56f8b4e
Create Date: 2020-09-28 16:05:42.791389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '345250e383fd'
down_revision = '86dee56f8b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('puppy_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['puppy_id'], ['puppies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('owners')
    # ### end Alembic commands ###
